"""Load, render and verify the guide-option support inventory."""

import argparse
import json
import re
import sys
import textwrap
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path
from typing import Any, cast

from conclear.catalog import GUIDE_URL, load_catalog
from conclear.errors import ConClearError, OperationalError
from conclear.guide_requirements import load_requirements, validate_guide_anchors
from conclear.identity import GUIDE_REVISION, GUIDE_TITLE, VERSION
from conclear.jsonutil import atomic_write_bytes, structure_depth_is_bounded

INVENTORY_SCHEMA_VERSION = 1
INVENTORY_PATH = Path(f"docs/guide-options-{VERSION}.md")
_OPTION_ID = re.compile(r"GO[0-9]{4}")
_REQUIREMENT_ID = re.compile(r"IG[0-9]{4}")
_STATUSES = frozenset({"supported", "manual", "unsupported", "out-of-scope"})


@dataclass(frozen=True, slots=True)
class GuideOption:
    """One guide option whose availability needs an explicit disposition."""

    option_id: str
    summary: str
    requirements: tuple[str, ...]
    status: str
    rationale: str
    reconsider_when: str
    checks: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class GuideOptionInventory:
    """Guide-option dispositions for one ConClear product version."""

    options: tuple[GuideOption, ...]


def load_guide_options(*, enforce_revision: bool = True) -> GuideOptionInventory:
    """Load and validate the shipped guide-option inventory."""
    resource = files("conclear.data").joinpath("guide-options.json")
    try:
        untrusted: Any = json.loads(resource.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError, RecursionError) as exc:
        raise OperationalError("Unable to load the guide-option inventory") from exc
    if not isinstance(untrusted, dict) or not structure_depth_is_bounded(untrusted):
        raise OperationalError("Guide-option inventory must be a JSON object")
    if set(untrusted) != {
        "schemaVersion",
        "productVersion",
        "guideRevision",
        "options",
    }:
        raise OperationalError("Guide-option inventory fields are malformed")
    if untrusted.get("schemaVersion") != INVENTORY_SCHEMA_VERSION:
        raise OperationalError("Unsupported guide-option inventory schema")
    if untrusted.get("productVersion") != VERSION:
        raise OperationalError("Guide-option product version does not match the build")
    if enforce_revision and untrusted.get("guideRevision") != GUIDE_REVISION:
        raise OperationalError("Guide-option revision does not match the build")
    raw_options = untrusted.get("options")
    if not isinstance(raw_options, list) or not raw_options:
        raise OperationalError("Guide-option entries are malformed")
    options = tuple(_option(value) for value in raw_options)
    identifiers = tuple(item.option_id for item in options)
    if identifiers != tuple(sorted(identifiers)):
        raise OperationalError("Guide options must be ordered by identifier")
    if len(identifiers) != len(set(identifiers)):
        raise OperationalError("Guide-option identifiers must be unique")
    if enforce_revision:
        active_checks = {item.check_id for item in load_catalog().checks}
        unknown_checks = sorted(
            {check for option in options for check in option.checks} - active_checks
        )
        if unknown_checks:
            raise OperationalError(
                "Guide options reference unknown checks: " + ", ".join(unknown_checks)
            )
        known = set(load_requirements().by_id())
        unknown = sorted(
            {item for option in options for item in option.requirements} - known
        )
        if unknown:
            raise OperationalError(
                "Guide options reference unknown requirements: " + ", ".join(unknown)
            )
    return GuideOptionInventory(options)


def render_guide_options(inventory: GuideOptionInventory | None = None) -> str:
    """Render deterministic guide-option documentation."""
    selected = inventory or load_guide_options()
    lines = [
        f"# ConClear {VERSION} guide-option support",
        "",
        "<!-- Generated by python -m conclear.guide_options. Do not edit by hand. -->",
        "",
        *_wrap(
            "This inventory records guide choices whose availability is not fully "
            f"visible from the check catalog. It is pinned to [{GUIDE_TITLE}]"
            f"({GUIDE_URL}) at revision `{GUIDE_REVISION}`. Each entry names the "
            "guide requirements it concerns; the conformance document links every "
            "requirement identifier to the guide."
        ),
    ]
    for option in selected.options:
        checks = ", ".join(f"`{item}`" for item in option.checks) or "None"
        requirements = ", ".join(f"`{item}`" for item in option.requirements)
        lines.extend(
            [
                "",
                f"## {option.option_id}: {option.summary}",
                "",
                *_field("Guide requirements", requirements),
                *_field("Status", f"`{option.status}`"),
                *_field("Checks", checks),
                *_field("Rationale", option.rationale),
                *_field("Reconsider when", option.reconsider_when),
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    """Generate the guide-option inventory or verify its committed copy."""
    parser = argparse.ArgumentParser(
        prog="python -m conclear.guide_options",
        description="Render or verify the guide-option support inventory.",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=INVENTORY_PATH)
    parser.add_argument("--guide", type=Path)
    arguments = parser.parse_args()
    try:
        inventory = load_guide_options()
        if arguments.guide is not None:
            validate_guide_anchors(arguments.guide)
        expected = render_guide_options(inventory)
    except ConClearError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if arguments.check:
        try:
            observed = arguments.output.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            return 1
        return 0 if observed == expected else 1
    atomic_write_bytes(arguments.output, expected.encode("utf-8"), mode=0o644)
    return 0


def _option(value: object) -> GuideOption:
    fields = {
        "id",
        "summary",
        "requirements",
        "status",
        "rationale",
        "reconsiderWhen",
        "checks",
    }
    if not isinstance(value, dict) or set(value) != fields:
        raise OperationalError("Guide-option inventory contains a malformed entry")
    item = cast(dict[str, object], value)
    option_id = _string(item, "id")
    status = _string(item, "status")
    if _OPTION_ID.fullmatch(option_id) is None:
        raise OperationalError("Guide-option identifiers must match GOnnnn")
    if status not in _STATUSES:
        raise OperationalError("Guide-option status is unsupported")
    requirements = _strings(item.get("requirements"))
    if not requirements or any(
        _REQUIREMENT_ID.fullmatch(entry) is None for entry in requirements
    ):
        raise OperationalError("Guide-option requirements must match IGnnnn")
    if list(requirements) != sorted(requirements):
        raise OperationalError("Guide-option requirements must be sorted")
    checks = _strings(item.get("checks"))
    return GuideOption(
        option_id=option_id,
        summary=_string(item, "summary"),
        requirements=requirements,
        status=status,
        rationale=_string(item, "rationale"),
        reconsider_when=_string(item, "reconsiderWhen"),
        checks=checks,
    )


def _string(value: dict[str, object], key: str) -> str:
    item = value.get(key)
    if not isinstance(item, str) or not item or "\n" in item:
        raise OperationalError(f"Guide-option field {key} is malformed")
    return item


def _strings(value: object) -> tuple[str, ...]:
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise OperationalError("Guide-option lists are malformed")
    result = tuple(cast(str, item) for item in value)
    if len(result) != len(set(result)):
        raise OperationalError("Guide-option lists contain duplicates")
    return result


def _wrap(
    value: str, *, initial_indent: str = "", subsequent_indent: str = ""
) -> list[str]:
    protected = re.sub(
        r"\[[^]]+\]\([^)]+\)",
        lambda match: match.group(0).replace(" ", "\0"),
        value,
    )
    return [
        line.replace("\0", " ")
        for line in textwrap.wrap(
            protected,
            width=80,
            initial_indent=initial_indent,
            subsequent_indent=subsequent_indent,
            break_long_words=False,
            break_on_hyphens=False,
        )
    ]


def _field(label: str, value: str) -> list[str]:
    prefix = f"- **{label}:** "
    return _wrap(value, initial_indent=prefix, subsequent_indent="  ")


if __name__ == "__main__":
    raise SystemExit(main())
